# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bio
email: mattmerr47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Matthew Merrill.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.piplotter.com" # the base hostname & protocol for your site
twitter_username: mattmerr47
github_username:  MatthewMerrill

portfolio:
  - AA:
    title: Project Title
    description: Description
    img: cabin.png
    notes:
      - AA:
        key: Website
        value: PiPlotter.com
        url: piplotter.com
    
# Build settings
markdown: kramdown
permalink: /:categories/:title/
